import type { IndustryVertical } from "@/lib/intelligence/industry-types"

export interface DomainCognitionPack {
  vertical: IndustryVertical
  label: string
  /** Nouns/phrases that belong in memo copy for this vertical */
  nativeLanguage: string[]
  /** Startup-template jargon that reads fake unless literally true for this vertical */
  forbiddenFrameworkLanguage: string[]
  economicDrivers: string[]
  procurementReality: string[]
  adoptionBarriers: string[]
  deploymentFriction: string[]
  incumbentBehavior: string[]
  switchingResistance: string[]
  operationalComplexity: string[]
  regulatoryPressure: string[]
  moatStructures: string[]
  distributionReality: string[]
  typicalFailurePatterns: string[]
  executionWedges: string[]
  pilotPaths: string[]
  founderDelusions: string[]
}

function pack(p: DomainCognitionPack): DomainCognitionPack {
  return p
}

const PACKS: Record<IndustryVertical, DomainCognitionPack> = {
  manufacturing_robotics: pack({
    vertical: "manufacturing_robotics",
    label: "Manufacturing / robotics / factory automation",
    nativeLanguage: [
      "OEE",
      "cycle time",
      "changeover",
      "scrap rate",
      "takt",
      "throughput",
      "uptime",
      "MTBF",
      "MTTR",
      "line clearance",
      "safety interlock",
      "EOL test",
      "commissioning",
      "PLC",
      "edge inference",
      "work cell",
      "capability study",
      "PPAP",
      "buy-off",
    ],
    forbiddenFrameworkLanguage: [
      "invite geometry",
      "liquidity",
      "disintermediation",
      "two-sided density",
      "viral loop",
      "ritual density",
      "creator supply",
    ],
    economicDrivers: [
      "Labor shortage + wage inflation force measurable minutes saved per station.",
      "Quality escapes and recalls dominate ROI math versus incremental SaaS fees.",
      "CapEx cycles gate deployments — finance cares about depreciation and utilization.",
    ],
    procurementReality: [
      "Plant engineering + EHS + IT often disagree; procurement runs RFQs with proof-of-run requirements.",
      "Incumbent integrators (Fanuc, ABB ecosystem, SI partners) own budget narratives.",
    ],
    adoptionBarriers: [
      "Production lines cannot tolerate experiments that stop the line.",
      "Union/work rules and safety certification constrain how fast software changes behavior.",
    ],
    deploymentFriction: [
      "On-floor networking, OT security reviews, change-control windows, spare-part logistics.",
      "Retrofitting brownfield lines beats greenfield dreams.",
    ],
    incumbentBehavior: [
      "Robot OEMs and automation SIs bundle software into hardware/service contracts.",
      "MES/MOM vendors upsell analytics modules tied to existing historians.",
    ],
    switchingResistance: [
      "Programs are tuned per SKU; switching vendors risks yield regressions.",
      "Maintenance techs trust vendors who answer 3am calls.",
    ],
    operationalComplexity: [
      "Multi-variant builds, tooling swaps, quality sampling plans — software must map messy reality.",
    ],
    regulatoryPressure: [
      "OSHA/machine guarding; regional factory regs; customer audit trails for automotive/medical suppliers.",
    ],
    moatStructures: [
      "Validated performance data on named SKUs + certified integrations + SI channel.",
      "Latency/reliability on the shop floor beats model accuracy demos.",
    ],
    distributionReality: [
      "Sell through automation integrators, OEM channels, or paid pilots on one line with measurable KPI hooks.",
    ],
    typicalFailurePatterns: [
      "Pretty UX with no quantified throughput/scrap delta.",
      "Underestimating integration hours and OT firewall politics.",
    ],
    executionWedges: [
      "One repeatable defect class with ROI calculator tied to scrap dollars.",
      "Shadow run alongside incumbent QC without blocking production.",
    ],
    pilotPaths: [
      "Paid pilot on a single cell with success criteria in downtime/scrap — expand line-by-line.",
    ],
    founderDelusions: [
      "Factories will adopt fast like devtools PLG.",
      "Computer vision accuracy alone wins without workflow + liability coverage.",
    ],
  }),

  industrial_infra: pack({
    vertical: "industrial_infra",
    label: "Industrial infrastructure / OT-heavy systems",
    nativeLanguage: ["uptime SLA", "trip events", "historian", "PID loop", "process upset", "yield", "flare stack"],
    forbiddenFrameworkLanguage: ["invite geometry", "organic invites", "social graph"],
    economicDrivers: ["Unplanned downtime cost dominates licensing.", "Energy input costs swing economics."],
    procurementReality: ["EPCs and owner-operators run multi-year vendor qualification."],
    adoptionBarriers: ["Cannot experiment on live process without redundancy plans."],
    deploymentFriction: ["Brownfield protocols, vendor silos, cyber segmentation."],
    incumbentBehavior: ["Incumbent DCS/PLC vendors bundle monitoring."],
    switchingResistance: ["Rewiring control philosophy is capital-risky."],
    operationalComplexity: ["Safety interlocks + alarm floods + operator habits."],
    regulatoryPressure: ["Environmental reporting; regional industrial compliance."],
    moatStructures: ["Certified interoperability + incident response muscle."],
    distributionReality: ["Channel partners and proof on pilot units."],
    typicalFailurePatterns: ["Dashboard without control-plane trust."],
    executionWedges: ["Alarm rationalization ROI; measurable MTTR reduction."],
    pilotPaths: ["Non-critical subsystem first with mirrored KPIs."],
    founderDelusions: ["Cloud-only solves OT without air-gap politics."],
  }),

  logistics: pack({
    vertical: "logistics",
    label: "Logistics / supply chain / fulfillment",
    nativeLanguage: ["SLA", "dock turns", "cube utilization", "pick accuracy", "inventory turns", "freight audit"],
    forbiddenFrameworkLanguage: ["ritual density", "creator economy"],
    economicDrivers: ["Labor availability at docks; fuel and freight rates swing margins."],
    procurementReality: ["RFP scorecards with SLA penalties; incumbent 3PL contracts."],
    adoptionBarriers: ["Cannot disrupt peak season flows."],
    deploymentFriction: ["WMS integrations, scanner workflows, labor training."],
    incumbentBehavior: ["Large 3PLs bundle labor + software."],
    switchingResistance: ["Operational risk if inventory accuracy drops."],
    operationalComplexity: ["Exceptions handling — damaged freight, partial picks."],
    regulatoryPressure: ["DOT/HOS; customs for cross-border."],
    moatStructures: ["Network density + reliable ETAs + claims handling."],
    distributionReality: ["Pilot site or lane-specific rollout."],
    typicalFailurePatterns: ["Map-only UX without scan-verified inventory truth."],
    executionWedges: ["Shrink measurable pilferage or cut dwell time at gate."],
    pilotPaths: ["One warehouse module with parallel KPI reporting."],
    founderDelusions: ["Uber-for-X without asset handler economics."],
  }),

  healthcare: pack({
    vertical: "healthcare",
    label: "Healthcare / clinical software & services",
    nativeLanguage: [
      "workflow burden",
      "clinical liability",
      "reimbursement",
      "coding",
      "prior auth",
      "payer mix",
      "SOAP note",
      "order set",
      "peer review",
    ],
    forbiddenFrameworkLanguage: ["liquidity", "take rate", "invite geometry"],
    economicDrivers: ["Reimbursement cuts vs labor shortage in clinical staff."],
    procurementReality: ["Committees: CMIO, nursing, compliance, IT security."],
    adoptionBarriers: ["Clinicians punish extra clicks; burnout caps training."],
    deploymentFriction: ["EHR integration depth (FHIR reality vs vendor sandboxes)."],
    incumbentBehavior: ["Epic/Cerner orbit; vertical SaaS bundles."],
    switchingResistance: ["Patient safety fears + retraining costs."],
    operationalComplexity: ["Mixed inpatient/outpatient workflows."],
    regulatoryPressure: ["HIPAA; FDA if device; state privacy."],
    moatStructures: ["Evidence + credentialing + payer partnerships."],
    distributionReality: ["Sell through IDNs or specialty clinics with measurable outcome metrics."],
    typicalFailurePatterns: ["AI demo without liability stance + workflow integration."],
    executionWedges: ["Measurable minutes saved per encounter + quality metric tie-in."],
    pilotPaths: ["One department go-live with IRB-friendly measurement."],
    founderDelusions: ["Doctors will adopt because accuracy went up on slides."],
  }),

  biotech: pack({
    vertical: "biotech",
    label: "Biotech / life science tools & therapeutics",
    nativeLanguage: ["assay validation", "GxP", "IND-enabling", "CRO handoff", "lot release"],
    forbiddenFrameworkLanguage: ["PLG motion", "invite loop"],
    economicDrivers: ["Capital intensity + milestone funding gates."],
    procurementReality: ["Vendor qualification for regulated workflows."],
    adoptionBarriers: ["Scientific skepticism without reproducibility packets."],
    deploymentFriction: ["Lab protocols + freezer logistics + contamination risk."],
    incumbentBehavior: ["Incumbent instruments locked with consumables."],
    switchingResistance: ["Validated methods locked in filings."],
    operationalComplexity: ["Batch variability + QC documentation."],
    regulatoryPressure: ["FDA/EMA pathways dominate timelines."],
    moatStructures: ["IP + reproducible assay + reference datasets."],
    distributionReality: ["Academic early adopters → pharma partnerships."],
    typicalFailurePatterns: ["Science fiction timelines and capex underestimates."],
    executionWedges: ["Partner with named lab for co-authored validation."],
    pilotPaths: ["Fee-for-sample pilots with predefined endpoints."],
    founderDelusions: ["Software alone replaces bench proof."],
  }),

  fintech: pack({
    vertical: "fintech",
    label: "Fintech / money movement / embedded finance",
    nativeLanguage: [
      "KYC",
      "AML",
      "ledger",
      "settlement",
      "chargeback",
      "BIN",
      "sponsor bank",
      "underwriting",
      "fraud ring",
      "PCI scope",
    ],
    forbiddenFrameworkLanguage: ["OEE", "scrap rate", "feed engagement"],
    economicDrivers: ["Net interest margin + fraud losses + compliance fixed costs."],
    procurementReality: ["Bank partner diligence; sponsor bank appetite cycles."],
    adoptionBarriers: ["Trust + regulatory uncertainty + core banking inertia."],
    deploymentFriction: ["PCI segmentation; state licensing; audits."],
    incumbentBehavior: ["Issuers bundle rewards + APIs + risk scoring."],
    switchingResistance: ["Accounts + autopay + fraud history."],
    operationalComplexity: ["Dispute queues + SAR workflows."],
    regulatoryPressure: ["AML/KYC; open banking rules; consumer protection."],
    moatStructures: ["Risk data flywheel + licensing + distribution partnerships."],
    distributionReality: ["BIN sponsorship + vertical embeds + payroll rails."],
    typicalFailurePatterns: ["Thin wrapper with no fraud story."],
    executionWedges: ["One wedge merchant vertical with measurable fraud delta."],
    pilotPaths: ["Shadow mode scoring before touching money movement."],
    founderDelusions: ["We'll dodge compliance until scale."],
  }),

  cybersecurity: pack({
    vertical: "cybersecurity",
    label: "Cybersecurity",
    nativeLanguage: ["blast radius", "mean time to contain", "detection fidelity", "alert fatigue", "coverage"],
    forbiddenFrameworkLanguage: ["creator economy", "liquidity"],
    economicDrivers: ["Breach insurance + regulatory fines shift budgets."],
    procurementReality: ["Security architecture review + purple-team bake-offs."],
    adoptionBarriers: ["False positives burn SOC credibility."],
    deploymentFriction: ["Agent deployment across heterogeneous estates."],
    incumbentBehavior: ["Incumbent suites bundle EDR/SIEM/SOAR."],
    switchingResistance: ["Playbooks tuned to incumbent alarms."],
    operationalComplexity: ["Multi-cloud + legacy agents."],
    regulatoryPressure: ["SEC disclosure; sector regulators."],
    moatStructures: ["Detection efficacy proof + channel MSSPs."],
    distributionReality: ["Bottom-up trial in SOC + enterprise expansion."],
    typicalFailurePatterns: ["ML buzz without measurable incident reduction."],
    executionWedges: ["Kill one high-volume false positive class."],
    pilotPaths: ["Read-only mirror of SOC queues with labeled outcomes."],
    founderDelusions: ["SOC will tolerate noisy alerts temporarily."],
  }),

  developer_tools: pack({
    vertical: "developer_tools",
    label: "Developer tools / infra software",
    nativeLanguage: ["TTFV", "semver", "migration tax", "CLI ergonomics", "SLO", "runbook"],
    forbiddenFrameworkLanguage: ["prior authorization", "scrap rate"],
    economicDrivers: ["Engineering time saved vs switching cost."],
    procurementReality: ["Bottom-up adoption + security review for enterprise."],
    adoptionBarriers: ["Migration effort beats marginal DX gains."],
    deploymentFriction: ["CI integration + secrets handling."],
    incumbentBehavior: ["Hyperscaler bundles similar surfaces."],
    switchingResistance: ["Code wired to SDK semantics."],
    operationalComplexity: ["Multi-region reliability expectations."],
    regulatoryPressure: ["Export controls for cryptography."],
    moatStructures: ["Workflow lock-in + ecosystem plugins."],
    distributionReality: ["OSS funnel → paid seats."],
    typicalFailurePatterns: ["Thin GUI over OSS without retention."],
    executionWedges: ["Own one CI bottleneck path."],
    pilotPaths: ["Design partner commits issue backlog + uptime SLA."],
    founderDelusions: ["Developers adopt fast therefore enterprise procurement vanishes."],
  }),

  ai_infrastructure: pack({
    vertical: "ai_infrastructure",
    label: "AI infrastructure / ML platform",
    nativeLanguage: ["cold start latency", "tokens/sec", "eval regression", "GPU fragmentation", "quantization"],
    forbiddenFrameworkLanguage: ["clinical liability", "dock turns"],
    economicDrivers: ["Inference COGS vs model quality; GPU spot volatility."],
    procurementReality: ["Platform engineering owns standards."],
    adoptionBarriers: ["Eval trust + vendor lock fear."],
    deploymentFriction: ["Multi-cloud GPU quotas + data egress."],
    incumbentBehavior: ["Cloud ML suites + foundation APIs."],
    switchingResistance: ["Pipelines wired to vendor SDKs."],
    operationalComplexity: ["Drift monitoring + rollback discipline."],
    regulatoryPressure: ["Copyright/training data disputes."],
    moatStructures: ["Benchmark leadership + reliability + enterprise SSO."],
    distributionReality: ["OSS core → hosted premium."],
    typicalFailurePatterns: ["Benchmark theater without prod incidents survived."],
    executionWedges: ["Measurable latency/cost win on named workload."],
    pilotPaths: ["Canary routing fraction with rollback triggers."],
    founderDelusions: ["Cheaper GPUs solve everything."],
  }),

  saas: pack({
    vertical: "saas",
    label: "Horizontal B2B SaaS",
    nativeLanguage: ["seat expansion", "workflow wedge", "implementation hours", "renewal risk"],
    forbiddenFrameworkLanguage: ["OEE", "prior authorization"],
    economicDrivers: ["ROI vs incumbent suites; expansion revenue quality."],
    procurementReality: ["Security review + procurement tiers."],
    adoptionBarriers: ["Change management inside departments."],
    deploymentFriction: ["Integrations + SSO + data mapping."],
    incumbentBehavior: ["Suite bundling + enterprise agreements."],
    switchingResistance: ["Embedded workflows + exports fear."],
    operationalComplexity: ["Multi-tenant reliability + permissions sprawl."],
    regulatoryPressure: ["Sector-specific (finance/health) when selling there."],
    moatStructures: ["Integration mesh + admin density."],
    distributionReality: ["PLG + sales-assist hybrid common."],
    typicalFailurePatterns: ["Feature parity chasing without wedge KPI."],
    executionWedges: ["Own one measurable KPI for one role."],
    pilotPaths: ["Paid pilot with success metrics in contract."],
    founderDelusions: ["Better UX wins without distribution wedge."],
  }),

  smb_software: pack({
    vertical: "smb_software",
    label: "SMB software",
    nativeLanguage: ["quick setup", "accountant channel", "cash flow", "no IT department"],
    forbiddenFrameworkLanguage: ["six-month security review"],
    economicDrivers: ["Price sensitivity + churn vs ARPU."],
    procurementReality: ["Owner-led; shallow evaluation cycles."],
    adoptionBarriers: ["Time poverty; low training tolerance."],
    deploymentFriction: ["Payments + payroll integrations."],
    incumbentBehavior: ["QuickBooks / Square or vertical champions."],
    switchingResistance: ["Historical records migration fear."],
    operationalComplexity: ["Support load explodes at scale."],
    regulatoryPressure: ["Sales tax / labor rules."],
    moatStructures: ["Channel partnerships + compliance depth at SMB price."],
    distributionReality: ["Partners + local installers + ads."],
    typicalFailurePatterns: ["Enterprise roadmap envy kills focus."],
    executionWedges: ["Win one vertical workflow completely."],
    pilotPaths: ["14-day measurable outcome trial."],
    founderDelusions: ["SMB will tolerate enterprise complexity for ‘power’."],
  }),

  enterprise_workflow: pack({
    vertical: "enterprise_workflow",
    label: "Enterprise workflow / collaboration inside large orgs",
    nativeLanguage: ["Records retention", "permissions model", "audit trail", "shared services"],
    forbiddenFrameworkLanguage: ["scrap rate", "take rate"],
    economicDrivers: ["Seat consolidation vs productivity lift."],
    procurementReality: ["Security + legal + IT architecture boards."],
    adoptionBarriers: ["Shadow IT competition + change mgmt."],
    deploymentFriction: ["Identity federation + DLP."],
    incumbentBehavior: ["Microsoft/Google suites expand."],
    switchingResistance: ["Integrations + compliance posture."],
    operationalComplexity: ["Multi-geo rollouts."],
    regulatoryPressure: ["Industry-specific records rules."],
    moatStructures: ["Compliance + enterprise workflow depth."],
    distributionReality: ["Land-and-expand inside departments."],
    typicalFailurePatterns: ["Collaboration theater without admin adoption."],
    executionWedges: ["Kill one painful approval chain."],
    pilotPaths: ["BU-scoped rollout with audit metrics."],
    founderDelusions: ["Virality fixes enterprise adoption."],
  }),

  marketplaces: pack({
    vertical: "marketplaces",
    label: "Marketplaces / two-sided platforms",
    nativeLanguage: ["liquidity", "cold start", "take rate", "multi-homing", "trust & safety"],
    forbiddenFrameworkLanguage: ["OEE", "clinical liability"],
    economicDrivers: ["Cross-side density + disintermediation risk + subsidy math."],
    procurementReality: ["Often consumer-led; ops-heavy categories need sales."],
    adoptionBarriers: ["Chicken-and-egg + fraud rings."],
    deploymentFriction: ["Payments + payouts + chargebacks."],
    incumbentBehavior: ["Brand aggregators + thin-margin races."],
    switchingResistance: ["Reputation + habit + listing inventory."],
    operationalComplexity: ["Moderation + supply quality variance."],
    regulatoryPressure: ["Labor classification; sector regs."],
    moatStructures: ["Winner-take-most local liquidity — rarely global generic."],
    distributionReality: ["Geo wedges + supply-first or demand-first discipline."],
    typicalFailurePatterns: ["National launch before local liquidity."],
    executionWedges: ["Depth in one micro-market before expansion."],
    pilotPaths: ["Deposit-backed pilots; fake-door with refunds."],
    founderDelusions: ["Marketing fixes structural thin liquidity."],
  }),

  consumer_social: pack({
    vertical: "consumer_social",
    label: "Consumer social / UGC products",
    nativeLanguage: ["retention curve", "moderation load", "creator payout", "notification decay"],
    forbiddenFrameworkLanguage: ["procurement friction", "RFQ"],
    economicDrivers: ["Ad ARPU vs sub willingness; moderation COGS."],
    procurementReality: ["None — consumer adoption curves dominate."],
    adoptionBarriers: ["Cold start attention markets."],
    deploymentFriction: ["App review + policy risk."],
    incumbentBehavior: ["Incumbents copy features fast."],
    switchingResistance: ["Graph + content archive."],
    operationalComplexity: ["Trust/safety scale."],
    regulatoryPressure: ["Age gating; privacy; speech regimes."],
    moatStructures: ["Rare — habit + culture pockets."],
    distributionReality: ["Paid UA + creator deals + loops."],
    typicalFailurePatterns: ["Feature novelty without durable habit."],
    executionWedges: ["Brutally narrow wedge community."],
    pilotPaths: ["One campus/subculture density test."],
    founderDelusions: ["Invite mechanics fix retention."],
  }),

  creator_economy: pack({
    vertical: "creator_economy",
    label: "Creator economy / audience monetization",
    nativeLanguage: ["GMV", "take rate", "payout latency", "chargeback", "audience overlap"],
    forbiddenFrameworkLanguage: ["PLC programming"],
    economicDrivers: ["Take rate vs churn; payout costs."],
    procurementReality: ["Creators behave like SMBs — deal fatigue."],
    adoptionBarriers: ["Multi-platform identity."],
    deploymentFriction: ["Payments compliance + tax reporting."],
    incumbentBehavior: ["YouTube/TikTok/Patreon ecosystems."],
    switchingResistance: ["Audience portability limits."],
    operationalComplexity: ["Disputes + content risk."],
    regulatoryPressure: ["AML when moving money."],
    moatStructures: ["Workflow lock-in + payouts reliability."],
    distributionReality: ["Creator partnerships + niche communities."],
    typicalFailurePatterns: ["Generic tipping jar without differentiated workflow."],
    executionWedges: ["Own one monetization primitive deeply."],
    pilotPaths: ["Cohort of creators with SLA-ed payouts."],
    founderDelusions: ["Passion beats payout reliability."],
  }),

  ecommerce: pack({
    vertical: "ecommerce",
    label: "E-commerce / DTC",
    nativeLanguage: ["contribution margin", "returns rate", "SKU economics", "CAC payback"],
    forbiddenFrameworkLanguage: ["clinical liability"],
    economicDrivers: ["CAC/LTV + inventory turns + returns leakage."],
    procurementReality: ["Merchant evaluates like P&L owner."],
    adoptionBarriers: ["Brand trust + logistics reliability."],
    deploymentFriction: ["3PL + inventory systems."],
    incumbentBehavior: ["Amazon scale + ads marketplace."],
    switchingResistance: ["Reviews + Prime habits."],
    operationalComplexity: ["Ops-heavy SKUs explode support."],
    regulatoryPressure: ["Product safety; payments compliance."],
    moatStructures: ["Brand + supply exclusives rare — mostly execution."],
    distributionReality: ["Paid social + retail wholesale pulls."],
    typicalFailurePatterns: ["Blitzscaling ads without repeat purchase proof."],
    executionWedges: ["Hero SKU repeat purchase before catalog sprawl."],
    pilotPaths: ["Limited geography inventory test."],
    founderDelusions: ["Brand story substitutes unit economics."],
  }),

  education: pack({
    vertical: "education",
    label: "Education / learning systems",
    nativeLanguage: ["curriculum alignment", "seat licenses", "district procurement", "equity gaps"],
    forbiddenFrameworkLanguage: ["take rate on riders"],
    economicDrivers: ["Budget cycles + evidence requirements."],
    procurementReality: ["Long cycles; pilot-friendly summers."],
    adoptionBarriers: ["Teacher time budget + union/parent politics."],
    deploymentFriction: ["Roster + privacy + device heterogeneity."],
    incumbentBehavior: ["Incumbent LMS + publishers."],
    switchingResistance: ["Curriculum lock-in."],
    operationalComplexity: ["Implementation science matters."],
    regulatoryPressure: ["FERPA/COPPA; accessibility."],
    moatStructures: ["Evidence + references + channel."],
    distributionReality: ["District pilots → expansion."],
    typicalFailurePatterns: ["Engagement metrics without learning outcomes."],
    executionWedges: ["Measurable outcome on one standardized pain."],
    pilotPaths: ["Single district cohort with principal sponsor."],
    founderDelusions: ["Teachers adopt because AI is clever."],
  }),

  climate_energy: pack({
    vertical: "climate_energy",
    label: "Climate / energy transition",
    nativeLanguage: ["LCOE", "interconnection queue", "PPA", "ITC", "REC"],
    forbiddenFrameworkLanguage: ["invite geometry"],
    economicDrivers: ["Policy incentives + commodity equipment pricing."],
    procurementReality: ["Developer/EPC procurement + financing partners."],
    adoptionBarriers: ["Interconnection timelines + permitting."],
    deploymentFriction: ["Site surveys + utility coordination."],
    incumbentBehavior: ["Utilities + OEM warranties."],
    switchingResistance: ["Long asset life — retrofit inertia."],
    operationalComplexity: ["Weather/load variability."],
    regulatoryPressure: ["Permitting + interconnect rules."],
    moatStructures: ["Asset performance data + financing relationships."],
    distributionReality: ["Developer partnerships + installer networks."],
    typicalFailurePatterns: ["Science projects without financing path."],
    executionWedges: ["One geography with modeled savings packet."],
    pilotPaths: ["Paid feasibility + metered before scale deploy."],
    founderDelusions: ["Policy tailwinds guarantee margins."],
  }),

  deeptech: pack({
    vertical: "deeptech",
    label: "Deeptech / atoms-heavy innovation",
    nativeLanguage: ["yield ramp", "fab cycle", "characterization", "TRL"],
    forbiddenFrameworkLanguage: ["PLG", "SEO flywheel"],
    economicDrivers: ["Long R&D + capex before revenue."],
    procurementReality: ["Few qualified buyers; certification gates."],
    adoptionBarriers: ["Science risk + integration risk."],
    deploymentFriction: ["Manufacturing scale-up."],
    incumbentBehavior: ["Incumbents acquire or outwait."],
    switchingResistance: ["Qualification timelines."],
    operationalComplexity: ["Supply chain + QA regimes."],
    regulatoryPressure: ["Export/defense dual-use controls."],
    moatStructures: ["IP + specialized manufacturing know-how."],
    distributionReality: ["Design wins with named OEMs."],
    typicalFailurePatterns: ["Slide-stage physics."],
    executionWedges: ["Customer-funded milestone proofs."],
    pilotPaths: ["Paid evaluation units with acceptance tests."],
    founderDelusions: ["Software multiples apply to atoms businesses."],
  }),
}

export function getDomainPack(v: IndustryVertical): DomainCognitionPack {
  return PACKS[v] ?? PACKS.saas
}

export function formatDomainPackForPrompt(v: IndustryVertical): string {
  const p = getDomainPack(v)
  const lines = [
    `DOMAIN_LENS: ${p.label}`,
    `Native vocabulary (prefer): ${p.nativeLanguage.slice(0, 14).join("; ")}`,
    `Forbidden template vocabulary for this domain unless literally true: ${p.forbiddenFrameworkLanguage.join("; ")}`,
    `Economic drivers: ${p.economicDrivers.join(" ")}`,
    `Procurement / buyer reality: ${p.procurementReality.join(" ")}`,
    `Adoption barriers: ${p.adoptionBarriers.join(" ")}`,
    `Deployment friction: ${p.deploymentFriction.join(" ")}`,
    `Incumbent behavior: ${p.incumbentBehavior.join(" ")}`,
    `Switching resistance: ${p.switchingResistance.join(" ")}`,
    `Operational complexity: ${p.operationalComplexity.join(" ")}`,
    `Regulatory pressure: ${p.regulatoryPressure.join(" ")}`,
    `Moat structures that sound real here: ${p.moatStructures.join(" ")}`,
    `Distribution reality: ${p.distributionReality.join(" ")}`,
    `Typical failure patterns: ${p.typicalFailurePatterns.join(" ")}`,
    `Execution wedges: ${p.executionWedges.join(" ")}`,
    `Believable pilots: ${p.pilotPaths.join(" ")}`,
    `Founder delusions common here: ${p.founderDelusions.join(" ")}`,
  ]
  return lines.join("\n")
}
